GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/5e3ebdc44908a739841fa578
###
delete http://localhost:3001/api/persons/2
###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{"name": "Testi Nimi 3","number": "04012345"}