GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/3
###
delete http://localhost:3001/api/persons/2
###
post http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Tapio Pertti",
    "number": "123"
}